name: Go Latest

on:
  schedule:
    # Run weekly on Mondays at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    name: Lint (Go Latest)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for git-validation

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
          cache: true

      - name: Install dependencies
        run: |
          go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@2b224c2cf4c9f261c22a16af7f8ca6408467f338
          go install github.com/vbatts/git-validation@7b60e35b055dd2eab5844202ffffad51d9c93922
          go install github.com/containerd/ltag@66e6a514664ee2d11a470735519fa22b1a9eaabd
          go install github.com/google/go-licenses/v2@3e084b0caf710f7bfead967567539214f598c0a2
          pip install yamllint
          sudo apt-get update && sudo apt-get install -y shellcheck

      - name: Lint Go (all platforms)
        run: make lint-go-all

      - name: Lint go.mod
        run: make lint-mod

      - name: Lint licenses (all platforms)
        run: make lint-licenses-all

      - name: Lint headers
        run: make lint-headers

      - name: Lint YAML
        run: make lint-yaml

      - name: Lint shell scripts
        run: make lint-shell

  test:
    name: Test (Go Latest)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
          cache: true

      - name: Start SSH agent
        run: |
          eval "$(ssh-agent -s)"
          echo "SSH_AUTH_SOCK=$SSH_AUTH_SOCK" >> $GITHUB_ENV
          echo "SSH_AGENT_PID=$SSH_AGENT_PID" >> $GITHUB_ENV

      - name: Run unit tests
        run: make test-unit

      - name: Run race detector tests
        run: make test-unit-race

  build:
    name: Build (Go Latest)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
          cache: true

      - name: Build binary
        run: make build

      - name: Verify binary
        run: ./bin/hadron --help
